language: node_js

node_js: 
  - "12"

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/reg_tests

before_script:
  - npm install
  - psql -c 'create database reg_tests;' -U postgres
  - psql -U postgres -d reg_tests -a -f reg.sql

services:
  - postgresql
  addons:
    postgresql: '9.4'
    apt:
      packages:
        -postgresql-server-dev-9.4

